In [1]:
#Model traning

model traning

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("data/gemstone.csv")

In [4]:
df.head()

   id  carat        cut color clarity  depth  table     x     y     z  price
0   0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [5]:
##dependending and independing features
x=df.drop(labels=['price'],axis=1)
y=df[['price']]

In [6]:
y

        price
0       13619
1       13387
2        2772
3         666
4       14453
...       ...
193568   1130
193569   2874
193570   3036
193571    681
193572   2258

[193573 rows x 1 columns]

In [7]:
x

            id  carat        cut color clarity  depth  table     x     y     z
0            0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55
1            1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05
2            2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50
3            3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71
4            4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77
...        ...    ...        ...   ...     ...    ...    ...   ...   ...   ...
193568  193568   0.31      Ideal     D    VVS2   61.1   56.0  4.35  4.39  2.67
193569  193569   0.70    Premium     G    VVS2   60.3   58.0  5.75  5.77  3.47
193570  193570   0.73  Very Good     F     SI1   63.1   57.0  5.72  5.75  3.62
193571  193571   0.34  Very Good     D     SI1   62.9   55.0  4.45  4.49  2.81
193572  193572   0.71       Good     E     SI2   60.8   64.0  5.73  5.71  3.48

[193573 rows x 10 columns]

In [8]:
df.head()

   id  carat        cut color clarity  depth  table     x     y     z  price
0   0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [9]:
df=df.drop(labels=["id"],axis=1)

In [10]:
df.head()

   carat        cut color clarity  depth  table     x     y     z  price
0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [11]:
#defining which columns should be ordinal encoded ans which should be selected
 #ordinal encoding means the changing the string value in the numerical means catagorical data changed into ranking
catagorical_col=x.select_dtypes(include="object").columns
numerical_col=x.select_dtypes(exclude="object").columns

In [12]:
df["color"].unique()

array(['F', 'J', 'G', 'E', 'D', 'H', 'I'], dtype=object)

In [13]:
cut_catagories=['Premium', 'Very Good', 'Ideal', 'Good', 'Fair']
clarity_catagories=['VS2', 'SI2', 'VS1', 'SI1', 'IF', 'VVS2', 'VVS1', 'I1']
color_catagories=['F', 'J', 'G', 'E', 'D', 'H', 'I']

In [14]:
from sklearn.impute import SimpleImputer ##for handling the missing values of the data
from sklearn.preprocessing import StandardScaler ##handling feature sacling
from sklearn.preprocessing import OrdinalEncoder ## for ordinal encoding
#for creating pipelines 
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [15]:
## Numerical Pipeline
num_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())

    ]

)

# Categorigal Pipeline
cat_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('ordinalencoder',OrdinalEncoder(categories=[cut_catagories,color_catagories,clarity_catagories])),
    ('scaler',StandardScaler())
    ]

)

preprocessor=ColumnTransformer([
('num_pipeline',num_pipeline,numerical_col),
('cat_pipeline',cat_pipeline,catagorical_col)
])

In [16]:
#train_test spliting
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=30)

In [17]:
x_train=pd.DataFrame(preprocessor.fit_transform(x_train),columns=preprocessor.get_feature_names_out())
x_test=pd.DataFrame(preprocessor.transform(x_test),columns=preprocessor.get_feature_names_out())

In [18]:
x_train.head()

,num_pipeline__id,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,1.274919,-0.975439,-0.849607,-0.121531,-1.042757,-1.080970,-1.123150,0.652673,1.655662,1.604964
1,-1.102907,0.235195,1.833637,-0.121531,0.318447,0.279859,0.485354,1.687566,0.056195,0.481725
2,-0.997613,0.494617,0.815855,0.399800,0.570855,0.606458,0.673737,-1.417114,-0.476960,-0.079894
3,-1.173764,-1.018676,0.260701,0.921131,-1.214034,-1.244270,-1.195605,-1.417114,-0.476960,-1.203134
4,-0.914812,-0.953821,-0.664555,-0.642862,-1.069801,-1.044681,-1.094168,0.652673,-1.010116,1.604964

In [19]:
##model traning
from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [20]:
regression=LinearRegression()
regression.fit(x_train,y_train)

LinearRegression()

In [21]:
regression.coef_

array([[-1.76038520e-01,  6.54772305e+03, -2.36703831e+02,
        -1.79529877e+02, -2.12180557e+03, -5.49492317e+02,
        -3.49871010e+01, -1.08021321e+01, -1.81097599e+02,
         1.20515188e+02]])

In [22]:
regression.intercept_

array([3970.76628955])

In [23]:
import numpy as np
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [24]:
## Train multiple models

models={
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'Elasticnet':ElasticNet()
}
trained_model_list=[]
model_list=[]
r2_list=[]

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train,y_train)

    #Make Predictions
    y_pred=model.predict(x_test)

    mae, rmse, r2_square=evaluate_model(y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print("RMSE:",rmse)
    print("MAE:",mae)
    print("R2 score",r2_square*100)

    r2_list.append(r2_square)
    
    print('='*35)
    print('\n')

LinearRegression
Model Training Performance
RMSE: 1198.8288094732538
MAE: 726.0530257868502
R2 score 91.17707544818099
===================================


Lasso
Model Training Performance
RMSE: 1198.711697959888
MAE: 727.4438430668451
R2 score 91.17879915646931
===================================


Ridge
Model Training Performance
RMSE: 1198.8300003385098
MAE: 726.0818699021604
R2 score 91.17705791954064
===================================


Elasticnet
Model Training Performance
RMSE: 1631.1190648100303
MAE: 1134.3638110131233
R2 score 83.66686502682896
===================================